name: Salesforce CI Pipeline

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop


jobs:
  salesforce-validation:

    runs-on: ubuntu-latest

    steps:

      # Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4


      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install @salesforce/cli --global


      # Verify Salesforce CLI
      - name: Verify Salesforce CLI
        run: |
          sf --version


      # Create JWT Key File
      - name: Create JWT Key File
        shell: bash
        run: |
          echo "${{ secrets.SF_JWT_KEY }}" > server.key


      # Verify Key Filea
      - name: Verify Key File
        run: |
          ls -l server.key
          head -1 server.key
          tail -1 server.key


      # Authenticate Salesforce Org
      - name: Authenticate Salesforce
        run: |
          sf org login jwt \
            --client-id "${{ secrets.SF_CLIENT_ID }}" \
            --jwt-key-file server.key \
            --username "${{ secrets.SF_USERNAME }}" \
            --instance-url "${{ secrets.SF_INSTANCE_URL }}"
            --set-default

      # Display Authenticated Org
      - name: Display Org
        run: |
          sf org display

      # Display Repository Files
      - name: Display Repository Files
        run: |
          ls -la